### PR TITLE
Flow integration

### PR DESCRIPTION
**Pull request by lucasvdh**
# Flow integration
This PR adds flow integration to the `com.p1` app. Read issue #4 to see why I made this.

## Flow card triggers
Five new flow card triggers are added:

1. Current power changed `measure_power.consumed.changed`
2. Consumed power changed `meter_power.consumed.changed`
3. Current generated power changed `measure_power.generated.changed`
4. Generated power changed `meter_power.generated.changed`
5. Gas usage changed `gas_meter.consumed.changed`

Each trigger has the value, for which they were triggered, available as a token.

## Settings page
Added a settings page where timeouts for each trigger can be configured during which a trigger should not be fired again.

### CODE REVIEW

**Comment by lucasvdh** [comment]
It's work in progress

**Comment by lucasvdh** [comment]
Not sure why, but can't really seem to be able to get the settings working. They aren't updated when changed in the app management section. @koktaildotcom got any ideas?

All the other stuff seems to be working fine and I haven't ran into any performance issues as of yet.

**Comment by koktaildotcom** [comment]
The variable in the '.set' contains the correct value?

**Comment by lucasvdh** [comment]
I think so.. haven't really figured out an easy way to debug the settings page

**Comment by koktaildotcom** [comment]
Can't you add a 'console.log(variable) to verify?

**Comment by koktaildotcom** [comment]
I'll have a look once i've the time

**Comment by koktaildotcom** [comment]
You made some typos:

measured_power.generated.timeout should be:
**measure_power.generated.timeout**

gas_meter.consumed.timeout should be:
**meter_gas.consumed.timeout**

I've add the changes to master

**Comment by koktaildotcom** [comment]
Many thanks for your contribution!

I've some remarks:

- The flows cards are not triggered with a timeout of 10 seconds.
- Can you simplify the case switch in: device.js:76 by passing the key.
- Would be nice if you build the two arrays with key 'measure_power.consumed.changed' and 'measure_power.consumed.timeout' seperate without replace the keys

**Comment by lucasvdh** [comment]
> Many thanks for your contribution!
> 
> I've some remarks:
> 
> * The flows cards are not triggered with a timeout of 10 seconds.

Yeah I had some problems with persisting and loading the correct timeout values from the `Homey.ManagerSettings`. I still intend to look into that. I'll create a new PR once I've started. 

However the initial concern for which I created these timeouts, mainly performance issues, does not seem to be any issue at all. So it could also be an option to just completely remove it.

> * Can you simplify the case switch in: device.js:76 by passing the key.

Will look into that.

> * Would be nice if you build the two arrays with key 'measure_power.consumed.changed' and 'measure_power.consumed.timeout' seperate without replace the keys

Noted. Thought about it, just got a bit too lazy I guess.

**Comment by koktaildotcom** [comment]
Again, thanks for your contribution! I've submitted version 2.0.4 into the store.

**Pull request merged**
